### PR TITLE
Implement children function

### PR DESCRIPTION
**Pull request by Atsman**

### CODE REVIEW

**Comment by Atsman** [comment]
https://github.com/igrishaev/etaoin/issues/139

**Comment by igrishaev** [comment]
Thank you! Sorry for such a long time.

**Comment by Atsman** [comment]
I just thought, maybe it was better to do `child` for one result and `children` for multiple?

**Comment by igrishaev** [comment]
@Atsman right. Could you do that?

**Comment by Atsman** [comment]
sure

**Pull request merged**
