### PR TITLE
Refactor internal api

### PR DESCRIPTION
**Pull request by Atsman**

### CODE REVIEW

**Comment by igrishaev** [comment]
@Atsman thank you for your efforts, I'm travelling abroad with my family, will take a look a bit later.

**Comment by Atsman** [comment]
@igrishaev common let's merge all 3 prs, who else can review except you?

**Comment by Atsman** [comment]
Hey, what's up ? Can u provide feedback ?

**Comment by Atsman** [comment]
What about this one? Your opinion?

**Comment by Atsman** [comment]
pong

**Comment by igrishaev** [comment]
@Atsman sorry for the delay. Using a function is really better than a macro in that case. I appreciate 
your help.

**Comment by Atsman** [comment]
@igrishaev nice! thank you!

**Pull request merged**
