### PR TITLE
Make client timeout configurable

### PR DESCRIPTION
**Pull request by Atsman**

### CODE REVIEW

**Comment by Atsman** [comment]
https://github.com/igrishaev/etaoin/issues/142

**Comment by Atsman** [comment]
Common, let's not give that project die

**Comment by igrishaev** [comment]
Thank you!

**Comment by igrishaev** [comment]
@Atsman just a note: this project is pretty stable and is not going to die. Rare features do not mean that.

**Comment by Atsman** [comment]
@igrishaev i am happy to hear that

**Comment by Atsman** [comment]
can be closed

**Pull request merged**
