### PR TITLE
use actions for double-click

### PR DESCRIPTION
**Pull request by xlfe**
This fixes double click on chromedriver as per #367 

I wasn't sure what you meant by "We only need to validate all the existing drivers how do they behave." - any resources you can point me towards?

Thanks

### CODE REVIEW

**Comment by igrishaev** [comment]
@xlfe for the delay. I'll merge and test it, and if it's fine, will make a new release.

**Comment by igrishaev** [comment]
Tested with:

```clojure
(def c (chrome))

(go c "https://developer.mozilla.org/en-US/docs/Web/API/Element/dblclick_event")

(with-frame c {:class "sample-code-frame"}
              (double-click c {:tag "aside"}))
```

**Comment by igrishaev** [comment]
`[etaoin "0.4.6"]` is out! Thanks again!

**Comment by xlfe** [comment]
Awesome thank you!

**Pull request merged**
